### Install libraries

- Use pip if you are uisng windows
- Use pip3 if you are using macOS

In [1]:
#pip install numpy
#pip install pandas
#pip install scikit-learn

### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

### Load Dataset
- It is better to keep the dataset in the same folder in which you have your notebook, otherwise you have to enter the complete path

In [2]:
# load dataset
df = pd.read_csv("mldata.csv")
df.head()

   age  weight gender likeness   height
0   27    76.0   Male  Biryani  170.688
1   41    70.0   Male  Biryani      165
2   29    80.0   Male  Biryani      171
3   27   102.0   Male  Biryani      173
4   29    67.0   Male  Biryani      164

In [3]:
# Take relevant data
workshop_data = df[["age","weight","height"]]
workshop_data.head()

   age  weight   height
0   27    76.0  170.688
1   41    70.0      165
2   29    80.0      171
3   27   102.0      173
4   29    67.0      164

In [5]:
X = workshop_data.iloc[:, :-1].values #get a copy of dataset exclude last column
y = workshop_data.iloc[:, 1].values #get array of dataset in column 1st

In [6]:
X

array([[ 27.  ,  76.  ],
       [ 41.  ,  70.  ],
       [ 29.  ,  80.  ],
       [ 27.  , 102.  ],
       [ 29.  ,  67.  ],
       [ 28.  ,  46.  ],
       [ 27.  ,  64.3 ],
       [ 34.  ,  98.  ],
       [ 32.  ,  87.5 ],
       [ 22.  ,  80.  ],
       [ 29.  ,  65.  ],
       [ 29.  ,  78.  ],
       [ 23.  ,  62.  ],
       [ 28.  ,  74.  ],
       [ 25.  , 102.  ],
       [ 27.  ,  78.  ],
       [ 33.  ,  93.  ],
       [ 28.  ,  68.  ],
       [ 21.  ,  71.5 ],
       [ 25.  , 135.  ],
       [ 24.  ,  82.  ],
       [ 30.  ,  70.  ],
       [ 30.  ,  60.  ],
       [ 32.  ,  84.5 ],
       [ 30.  ,  65.  ],
       [ 25.  ,  70.  ],
       [ 34.  ,  59.  ],
       [ 32.  ,  78.  ],
       [ 24.  ,  68.  ],
       [ 30.  ,  62.  ],
       [ 21.  ,  58.  ],
       [ 31.  , 102.3 ],
       [ 22.  ,  64.  ],
       [ 19.  ,  50.  ],
       [ 30.  ,  75.  ],
       [ 27.  ,  77.  ],
       [ 34.  ,  82.72],
       [ 24.  ,  93.  ],
       [ 26.  ,  55.  ],
       [ 22.  ,  50.  ],
       [ 35.  ,  75.  ],
       [ 27.  ,  64.  ],
       [ 27.  ,  85.  ],
       [ 27.  ,  65.  ],
       [ 30.  ,  84.  ],
       [ 44.  ,  85.  ],
       [ 23.  ,  53.  ],
       [ 48.  ,  90.  ],
       [ 28.  ,  79.  ],
       [ 24.  ,  68.  ],
       [ 40.  ,  85.  ],
       [ 32.  ,  79.  ],
       [ 29.  ,  50.9 ],
       [ 27.  ,  68.5 ],
       [ 26.  , 130.  ],
       [ 30.  ,  63.  ],
       [ 27.  ,  93.  ],
       [ 23.  ,  59.  ],
       [ 28.  ,  76.  ],
       [ 22.  ,  76.  ],
       [ 23.  ,  60.  ],
       [ 26.  ,  63.  ],
       [ 30.  ,  60.  ],
       [ 31.  ,  75.  ],
       [ 30.  ,  70.  ],
       [ 21.  ,  65.  ],
       [ 20.  ,  70.  ],
       [ 26.  ,  55.  ],
       [ 35.  ,  65.  ],
       [ 38.  ,  72.6 ],
       [ 27.  ,  55.  ],
       [ 27.  ,  46.  ],
       [ 38.  ,  62.  ],
       [ 25.  ,  72.5 ],
       [ 25.  ,  55.5 ],
       [ 24.  ,  70.  ],
       [ 24.  ,  86.  ],
       [ 22.  ,  52.  ],
       [ 25.  ,  43.  ],
       [ 32.  ,  61.5 ],
       [ 22.  ,  76.  ],
       [ 27.  ,  60.  ],
       [ 22.  ,  62.  ],
       [ 37.  ,  77.  ],
       [ 30.  ,  65.  ],
       [ 27.  ,  50.  ],
       [ 33.  ,  91.  ],
       [ 25.  ,  75.  ],
       [ 38.  ,  81.5 ],
       [ 25.  ,  88.  ],
       [ 21.  ,  60.  ],
       [ 31.  ,  86.  ],
       [ 24.  ,  87.  ],
       [ 25.  ,  70.  ],
       [ 18.  ,  55.6 ],
       [ 24.  ,  86.  ],
       [ 35.  ,  82.  ],
       [ 44.  ,  70.  ],
       [ 30.  ,  60.  ],
       [ 32.  ,  50.  ],
       [ 25.  ,  62.  ],
       [ 29.  ,  71.  ],
       [ 24.  ,  55.  ],
       [ 29.  ,  78.  ],
       [ 35.  ,  72.  ],
       [ 46.  ,  75.  ],
       [ 32.  ,  10.92],
       [ 27.  ,  57.  ],
       [ 25.  ,  90.  ],
       [ 29.  ,  65.  ],
       [ 37.  ,  68.  ],
       [ 32.  ,  74.  ],
       [ 20.  ,  52.  ],
       [ 32.  ,  51.  ],
       [ 28.  ,  76.  ],
       [ 27.  ,  82.  ],
       [ 30.  ,  75.  ],
       [ 31.  ,  86.  ],
       [ 27.  ,  80.  ],
       [ 27.  ,  51.  ],
       [ 29.  ,  78.  ],
       [ 20.  ,  54.  ],
       [ 31.  ,  85.  ],
       [ 27.  ,  58.  ],
       [ 68.  ,  68.  ],
       [ 40.  ,  97.  ],
       [ 24.  ,  66.  ],
       [ 25.  ,  47.  ],
       [ 24.  ,  65.  ],
       [ 26.  ,  60.  ],
       [ 30.  ,  90.  ],
       [ 31.  ,  40.  ],
       [ 36.  ,  62.  ],
       [ 30.  ,  65.  ],
       [ 19.  ,  55.2 ],
       [ 23.  ,  71.  ],
       [ 25.  ,  55.  ],
       [ 27.  ,  54.  ],
       [ 28.  , 161.  ],
       [ 39.  , 102.  ],
       [ 43.  ,  85.  ],
       [ 25.  ,  59.  ],
       [ 28.  ,  83.  ],
       [ 28.  ,  46.  ],
       [ 20.  ,  53.  ],
       [ 23.  ,  62.  ],
       [ 25.  ,  55.  ],
       [ 26.  ,  76.  ],
       [ 31.  ,  68.  ],
       [ 32.  ,  57.  ],
       [ 21.  ,  81.  ],
       [ 31.  ,  80.  ],
       [ 28.  ,  68.  ],
       [ 28.  ,  63.4 ],
       [ 27.  ,  67.  ],
       [ 24.  ,  50.  ],
       [ 19.  ,  50.4 ],
       [ 34.  ,  58.  ],
       [ 22.  ,  67.  ],
       [ 27.  ,  75.  ],
       [ 31.  ,  86.  ],
       [ 33.  ,  86.  ],
       [ 33.  ,  46.7 ],
       [ 21.  ,  45.  ],
       [ 29.  ,   6.  ],
       [ 21.  ,  62.  ],
       [ 26.  ,  90.  ],
       [ 27.  , 101.  ],
       [ 42.  , 179.  ],
       [ 25.  ,  88.  ],
       [ 29.  ,  73.  ],
       [ 21.  ,  50.  ],
       [ 44.  ,  78.  ],
       [ 28.  ,  84.  ],
       [ 30.  ,  67.  ],
       [ 40.  ,  71.  ],
       [ 28.  ,  96.  ],
       [ 26.  ,  70.  ],
       [ 30.  ,  88.  ],
       [ 29.  ,  84.  ],
       [ 26.  ,  90.  ],
       [ 50.  ,  88.  ],
       [ 35.  ,  75.  ],
       [ 31.  ,  86.  ],
       [ 24.  ,  82.  ],
       [ 21.  ,  68.  ],
       [ 39.  ,  53.  ],
       [ 30.  ,  73.8 ],
       [ 32.  ,  80.  ],
       [ 29.  ,  74.  ],
       [ 27.  ,  80.  ],
       [ 31.  ,  54.  ],
       [ 27.  ,  62.  ],
       [ 25.  ,  64.  ],
       [ 34.  ,  82.  ],
       [ 40.  ,  80.  ],
       [ 34.  ,  79.  ],
       [ 20.  ,  40.  ],
       [ 32.  ,  74.  ],
       [ 34.  ,  98.  ],
       [ 31.  ,  86.  ],
       [ 24.  ,  57.  ],
       [ 28.  ,  65.  ],
       [ 30.  ,  75.  ],
       [ 28.  ,  56.  ],
       [ 20.  ,  78.  ],
       [ 27.  ,  88.  ],
       [ 28.  ,  62.  ],
       [ 24.  ,  75.  ],
       [ 27.  ,  85.  ],
       [ 37.  ,  80.  ],
       [ 28.  ,  74.  ],
       [ 24.  ,  45.  ],
       [ 33.  ,  74.  ],
       [ 29.  ,  88.2 ],
       [ 28.  ,  77.  ],
       [ 26.  ,  60.  ],
       [ 23.  ,  68.  ],
       [ 30.  ,  78.  ],
       [ 43.  ,  85.  ],
       [ 26.  ,  62.  ],
       [ 25.  ,  70.  ],
       [ 21.  ,  60.  ],
       [ 26.  ,  74.  ],
       [ 20.  ,  48.  ],
       [ 22.  ,  53.  ],
       [ 22.  ,  64.  ],
       [ 20.  ,  26.  ],
       [ 27.  ,  59.  ],
       [ 27.  ,  96.  ],
       [ 35.  ,  64.  ],
       [ 27.  ,  68.  ],
       [ 38.  ,  72.2 ],
       [ 25.  ,  66.  ],
       [ 36.  ,  68.  ],
       [ 20.  ,  48.  ],
       [ 30.  ,  50.  ],
       [ 24.  ,  60.  ],
       [ 22.  ,  50.  ],
       [ 27.  ,  63.  ],
       [ 31.  ,  60.  ],
       [ 26.  ,  70.  ],
       [ 40.  ,  80.  ],
       [ 25.  ,  65.  ],
       [ 33.  ,  56.  ]])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

In [13]:
# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [14]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [15]:
y_pred

array([ 87.  ,  50.  ,  72.5 ,  63.  ,  88.  ,  74.  ,  54.  ,  55.  ,
        57.  ,  70.  ,  82.  ,  58.  ,  88.  ,  72.2 ,  98.  ,  63.4 ,
        75.  ,  96.  ,  55.5 ,  72.  ,  74.  ,  85.  ,  75.  ,  80.  ,
        97.  ,  84.  ,  60.  ,  87.5 ,  74.  ,  82.  ,  84.  ,  66.  ,
        46.  ,  60.  ,  62.  ,  93.  ,  50.4 ,  55.  ,  64.  ,  90.  ,
        70.  ,  50.  ,  77.  ,  53.  ,  46.  ,  53.  ,  90.  ,  71.5 ,
        65.  ,  78.  ,  67.  ,  98.  ,  75.  ,  62.  ,  68.  ,  58.  ,
        10.92,  85.  ,  77.  ,  50.  , 102.  ,  46.7 ,  70.  ,  56.  ,
        60.  ,  62.  ,  48.  ,  88.  ,  53.  ,  93.  ,  90.  ,  73.  ,
        86.  ,  67.  ,  68.  ,  63.  ,  80.  ,  50.9 ,  70.  ,  59.  ,
        56.  ,  84.  ])

In [ ]:
# Visualizing the Training set results
viz_train = plt
viz_train.scatter(X_train[:,0], y_train, color='red')
viz_train.plot(X_train[:,0], regressor.predict(X_train[:,0]), color='blue')
viz_train.title('Age & Weight vs Height (Training set)')
viz_train.xlabel('Age & Weight')
viz_train.ylabel('Height')
viz_train.show()

# Visualizing the Test set results
viz_test = plt
viz_test.scatter(X_test, y_test, color='red')
viz_test.plot(X_train, regressor.predict(X_train[:,0]), color='blue')
viz_test.title('Age & Weight vs Height (Test set)')
viz_test.xlabel('Age & Weight')
viz_test.ylabel('Height')
viz_test.show()

In [ ]:
viz_train = plt
viz_train.scatter(X_train[:,0], y_train, color='red')
viz_train.plot(X_train[:,0], regressor.predict(X_train[:,0]), color='blue')
viz_train.title('Salary VS Experience (Training set)')
viz_train.xlabel('Year of Experience')
viz_train.ylabel('Salary')
viz_train.show()

# Visualizing the Test set results
viz_test = plt
viz_test.scatter(X_test, y_test, color='red')
viz_test.plot(X_train[:,0], regressor.predict(X_train[:,0]), color='blue')
viz_test.title('Salary VS Experience (Test set)')
viz_test.xlabel('Year of Experience')
viz_test.ylabel('Salary')
viz_test.show()